spring:
  application:
    name: chart

  datasource:
    url: jdbc:mysql://localhost:3306/easy_show_chart?serverTimezone=UTC
    username: root
    password: root
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10

  jpa:
    show-sql: true