spring:
  application:
    name: design

  data:
    mongodb:
      host: 192.168.8.148
      port: 27017
      database: easy_chart_design

  redis:
    host: 192.168.8.148
    password: 1234qwer
    database: 0

design:
  series:
    calc:
      jsName: calcjs/ChartCalculator.umd.min.js
      objectName: ChartCalculator
      methodName: parsePlusDesign