spring:
  application:
    name: design

  data:
    mongodb:
      host: 192.168.8.148
      port: 27017
      database: easy_chart_design

  redis:
    host: 192.168.8.148
    password: 1234qwer
    database: 0

  cache:
    type: redis
    redis:
      time-to-live: 24h
      cache-null-values: true
      use-key-prefix: true
      key-prefix: "ed:${spring.application.name}:springcache"

design:
  series:
    calc:
      jsName: calcjs/ChartCalculator.umd.min.js
      objectName: ChartCalculator
      methodName: parsePlusDesign