spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
            - Path='/api/'+serviceId+'/**'
          filters:
            - RewritePath='/api/'+serviceId+'/v1/(?<remaining>.*)', '/${remaining}'