spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easy_show_schedule?serverTimezone=UTC
    username: root
    password: root
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10

  jpa:
    show-sql: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName : easyShowQuartzScheduler
            instanceId: AUTO
          threadPool:
            threadCount: 10
          jobStore:
            isClustered: true