server:
  port: 9999

spring:
  application:
    name: eureka-service

eureka:
  server:
    #关闭自我保护，否则服务挂掉不踢出节点
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: @eureka.defaultZone@
  instance:
    prefer-ip-address: true
